management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /
      path-mapping:
        health: _health

  endpoint:
    health:
      show-details: always

  health:
    db:
      enabled: false

grafana:
  otlp:
    onprem:
      endpoint: http://tempo:4317
      protocol: grpc