management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: _health

  endpoint:
    health:
      show-details: always

  health:
    db:
      enabled: false
