management:
  endpoints:
    metrics:
      enables: true
    prometheus:
        enabled: true
    web:
      exposure:
        include: health,prometheus,metrics
      base-path: /
      path-mapping:
        health: _health

  endpoint:
    health:
      show-details: always

  health:
    db:
      enabled: false