management:
  endpoints:
    metrics:
      enables: true
    prometheus:
        enabled: true
    web:
      exposure:
        include: health,prometheus,metrics
      base-path: /
      path-mapping:
        health: _health

  endpoint:
    health:
      show-details: always

  health:
    db:
      enabled: false
  otlp:
    metrics:
      export:
        url: http://grafana-agent:4318/v1/metrics
        step: 10s
    traces:
      export:
        url: http://grafana-agent:4318/v1/traces
        step: 10s