global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
#      - targets: ['<springboot-app-host>:<springboot-app-port>']
      - targets: ['localhost:9090']
        metric_path: '/actuator/prometheus'

remote_write:
  - url: http://localhost:9009/api/v1/push